name: progenius
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ">=3.6.0 <4.0.0"
  flutter: ">=3.16.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.7
  get: ^4.6.6
  font_awesome_flutter: ^10.8.0
  change_app_package_name: ^1.1.0
  flutter_launcher_icons: ^0.13.1
  youtube_player_iframe: ^5.2.1
  no_screenshot: ^0.3.1
  http: ^1.3.0
  shared_preferences: ^2.5.1
  image_picker: ^1.1.2
  flutter_full_pdf_viewer_null_safe: ^1.0.0
  webview_flutter: ^4.10.0
  cached_network_image: ^3.4.1
  path_provider: ^2.1.5
  flutter_pdfview: ^1.3.2
  url_launcher: ^6.3.1
  http_parser: ^4.1.2
  fluttertoast: ^8.2.12
  permission_handler: ^12.0.0+1
  syncfusion_flutter_charts: ^30.1.37
  dio: ^5.8.0+1
  flutter_cache_manager: ^3.4.1
  get_storage: ^2.1.1
  firebase_core: ^3.8.1
  firebase_crashlytics: ^4.2.0
  firebase_analytics: ^11.3.5
 
 




 
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter_icons:
  android: true # Ensure this is set to true
  ios: true # Ensure this is set to true
  image_path: "assets/logo1.png" # Path to your app logo1pnmin_sdk_android: 21 # Minimum SDK version
 
  adaptive_icon_foreground: "assets/logo1.png" # Foreground icon for adaptive icons

  flutter_lints: ^5.0.0

flutter:

  
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/


